apiVersion: v1
kind: ConfigMap
metadata:
  name: casc-config
data:
  casc.yml: |
    jenkins:
      securityRealm:
        local:
          allowsSignup: false
          users:
          - id: admin
            password: admin
    unclassified:
      location:
        url: http://0.0.0.0:8080/
